# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d31149fdb08259788aa163bbf62c0ad618095bf93a9f74ee44cc312875ccacb8d16ecf2b971c605e014d1a5098bd4c021a701800c15447b9886005aeaa95d412

test:
  secret_key_base: 87986627300dcace754cc50a0e4b858f0e8742e122ccc1217316a48b889e42351361057ca7503c6e33eb0c5c0f098b87955c50796eca7f5deed2d241f0051243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
